### PR TITLE
Add Cmake & fix compile errors/warnings

### PR DESCRIPTION
**Pull request by kim366**
So I've added the necessary CMake files, which allow for fast building of this library. The use of global namespace math function is compiler/OS dependent and did not compile for me on Arch. Some `cmath` headers were missing too, which might not have been necessary on your system.

To build with cmake do the following (on Linux for g++ at least):
```
mkdir build
cd build
cmake ..
sudo make install
```

### CODE REVIEW

**Comment by kim366** [comment]
So I now added the building of examples which can be enabled with `-DBUILD_EXAMPLES=ON`

**Comment by Hapaxia** [comment]
Thank you for this. I appreciate this effort. I would like your CMake setup testing by someone (or more) else to make sure it works more widespread. I'll even attempt the test myself!

I'm unsure about this though because it separates the headers from the source files. For a library, this is great, and for anyone building Selba Ward in its entirely, this is good. However, this might be more accurately described a a collection rather than a library and another use of it is to only copy the two files required for each object. This is a little more cumbersome (but not that hard really) as you have to find them in two completely separate areas.
Maybe more people would use it as a library if it does have a CMake already though.

Note also that added the CMake building is one issue and the math headers/scope is another so the cmath and std:: prefixes should be removed from this PR and dealt with separately.

**Comment by kim366** [comment]
Ok, I'll attempt to separate the commits. It will still be possible to have both headers & sources in the same directory, actually, so I'll change that, if you like that better. It would be nice to let someone more experienced look over the CMake again, though, as I'm not a pro at writing these files and the syntax hash changed recently.

**Comment by Hapaxia** [comment]
I've fixed ( #18 ) the issue of the missing cmath inclusions and the std namespace prefixes that were also missing. You can now focus on just the CMake part.

Once you have the CMake PR ready, we can ask others to test it.

**Comment by kim366** [comment]
Thanks! I currently have some other stuff to work on, but I'll try to get back to this asap.

**Comment by Hapaxia** [comment]
Closing this due to inactivity for over a year.

**Comment by kim366** [comment]
Huh, already been a year :p

**Comment by ChrisThrasher** [comment]
Hi, I maintain the CMake scripts for SFML. Let me know if you’re still interested in CMake support and an accompanying CI pipeline.

**Comment by ChrisThrasher** [comment]
https://github.com/Hapaxia/SelbaWard/pull/41

Here's a basic CMake script and CI pipeline.

**Comment by Hapaxia** [comment]
Hi Chris. Yes, of course. I'll take a look at that right now!

**Pull request closed without merging**
