### PR TITLE
Fixed shaders were not compiling

### PR DESCRIPTION
**Pull request by naezith**
Shaders were not compiling, Using R literal strings now.

One compile error was subtraction between float and int,
`uniform float renderTargetHeight;` making this float fixed that.

Another one was `switch` is reserved word, replaced it with `if else` statements instead.

They all compile now.

### CODE REVIEW

**Comment by Hapaxia** [comment]
The switch command and implicit conversions between types should be fine within standard OpenGL.

Can you confirm whether you had these compilation troubles with standard OpenGL or OpenGL ES?

**Comment by naezith** [comment]
OpenGL

**Comment by Hapaxia** [comment]
Thanks.
That is an issue then. OpenGL does includes the switch keyword whereas ES has it as reserved.

A render target height can only ever be an integer so it makes sense to use one for the interface. It will just need explictly converting inside the shader.

Did you find that the R literals made an actual difference with compilation or was it just because it was clearer for you to work with?

As an afterthought, maybe OpenGL is working on an extremely early version. Just noticed that I haven't added the version numbers to the shaders...

Thank you again and I appreciate your involvement :)

**Comment by naezith** [comment]
Yeah probably it's a version issue. R literal made it easy to read/edit/fix.

**Comment by Hapaxia** [comment]
I've added the fix for these problems to the v1.2.1 patch: f901693a6a0cdc4b747b7272a0c162ea4739c23c

So, for this stuff:
Version numbers have been added to the shaders.
I also replaced switch with ifs to comply with the version I used for the shaders.
Shaders have been recompiled to "blocks of code" as before and have the same internal formatting.
The integer uniform has stayed as an integer but converted to a float before the calculation.

Feel free try out this version and see if works as expected for you now.
Thanks again for your involvement.

**Comment by naezith** [comment]
What's the point of making shaders unreadable? I won't be able to test it by the way, you can close this issue.

**Comment by Hapaxia** [comment]
The shaders are not supposed to be part of the main code; it's distracting since it's an entirely different language. They're included as strings, though, to avoid having to extra files just for those shaders, which would be the prefered way if not for portability.

No problem that you can't test it. I appreciate you bringing it to my attention; thank you!

**Pull request closed without merging**
