### PR TITLE
Add build script and CI pipeline

### PR DESCRIPTION
**Pull request by ChrisThrasher**
This CMake script will be very useful to those who want to use SelbaWard in their own CMake project. It will make integration much simpler. It also provides a convenient way of building the entire library and all of its examples without having ot invoke the compiler many times over and over again.

Using this CMake script I was able to make a CI pipeline which automatically builds SelbaWard for Windows, Linux, and macOS. This will run every time anyone makes a PR or pushes to the repository. If it succeeds then we can be sure that the library still builds.

The CMake script can be expanded in the future to support more things but this PR represents the minimal starting point. It's nice and simple as-is.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
I believe you will have to enable CI pipelines on this PR for the pipeline to run. After you do that the CI pipeline results will show up in this PR and all future PRs.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SelbaWard/actions/runs/5919830192/job/16050490227#step:9:17

By the way, a compiler warning caught a bug in PixelDisplay.cpp

```
[9/37] /usr/bin/clang++  -I/home/runner/work/SelbaWard/SelbaWard/SelbaWard/src -isystem /home/runner/work/SelbaWard/SelbaWard/sfml/install/include -O3 -DNDEBUG -MD -MT CMakeFiles/SelbaWard.dir/src/SelbaWard/PixelDisplay.cpp.o -MF CMakeFiles/SelbaWard.dir/src/SelbaWard/PixelDisplay.cpp.o.d -o CMakeFiles/SelbaWard.dir/src/SelbaWard/PixelDisplay.cpp.o -c /home/runner/work/SelbaWard/SelbaWard/SelbaWard/src/SelbaWard/PixelDisplay.cpp
/home/runner/work/SelbaWard/SelbaWard/SelbaWard/src/SelbaWard/PixelDisplay.cpp:583:53: warning: left operand of comma operator has no effect [-Wunused-value]
                        buffer.pixels[y * buffer.width + x] = m_pixels[x + rectangle.left, y + rectangle.top];
                                                                       ~ ^ ~~~~~~~~~~~~~~
```

This is a great example of how this CMake script and CI will catch more bugs. If we enable warnings-as-errors in CI then this will cause CI to fail and force whoever wrote that to fix it. I can add more compilers warnings to this library if you'd like.

**Comment by Hapaxia** [comment]
Hi again Chris and thank again for this!

I have little to no experience with continuous integration so you may have to be a bit patient with me to set this up.

That bug surprised me; I now need to investigate to see what it's supposed to be :D

**Comment by ChrisThrasher** [comment]
> I have little to no experience with continuous integration so you may have to be a bit patient with me to set this up.

The only set up on your part should just be some button that tells the GitHub project to enable GitHub Actions. Otherwise you don't have to change anything about how you're working.

**Comment by Hapaxia** [comment]
It seems that the repo is already giving GitHub Actions permission. If I merge this, will your pull request set up the action?
I'm guessing I can just merge this but do I need to do something else first?

**Comment by ChrisThrasher** [comment]
I'd expect there to be a button on this PR thread saying "approve actions" or something like that. You can see CI running in my fork of SelbaWard just fine so I think you're just forgetting to do something.

**Review by Hapaxia — APPROVED** [review]

**Comment by Hapaxia** [comment]
I have not done this before so not sure what I'm missing.
Apologies for getting stuck on such an obviously simple thing :(

The buttons I have at the bottom of the PR are "Add rule" (for approval from specific reviewers) and just "Merge pull request". It also says that Continuous integration has not been set up and there are some links to things describing how to make some.

Ah, just found the approval thing for the PR. Is that the one I needed to do - approve changes? and can I merge now or is something still missing?

**Comment by ChrisThrasher** [comment]
Approving the PR is different from enabling CI pipelines. Idk exactly what's going on.

**Comment by Hapaxia** [comment]
It looks like it's enabled by default and the "workflow(s) awaiting approval" button would be there if there is already a workflow to change so merging this should add the new workflow.

Are you happy for me to merge?

**Comment by ChrisThrasher** [comment]
Yeah I'm ready for this be merged. We can fix anything after the fact if I overlooked something.

**Comment by ChrisThrasher** [comment]
https://github.com/Hapaxia/SelbaWard/actions/runs/5929199373

It works! I hope this speeds up development and helps encourage more people to use the library.

**Comment by Hapaxia** [comment]
Yay! Thank you so much! I very much appreciate this!

May I ask, though, how come it's not flagging that compile bug in PixelDisplay or is that a separate check somewhere else?
I have the fix ready but I left it (for now) to see if I would be able to use it to find errors.
Or, does it only check modifications? Again, I'm quite new to this whole thing.

**Comment by ChrisThrasher** [comment]
It's not a hard failure because we're not using `-Werror` in CI. Compiler warnings are allowed to exist. If we really care about fixing compiler warnings then we need to enable warnings as errors.

**Comment by Hapaxia** [comment]
Ah right so it'll still "work" for people - and it might be intentional - so those checks would be better on our own compilers?

**Pull request merged**
